package ingestionworker

// RuleCatalogEntry is the user-visible metadata for one built-in finding
// rule. The connectors UI surfaces every entry alongside an on/off toggle
// backed by integration_connections.disabled_checks. This catalog is the
// SOLE source of truth for what shows up in the toggle list; adding a new
// rule means: (1) write the evaluator, (2) add it to Evaluate(), (3) add
// it to the corresponding supportedIngestionEventTypes provider, (4) add
// an entry here so it appears in the UI.
//
// Rules also carry detection-pack metadata so operators can reason about
// coverage in terms of curated, versioned bundles. PackID points into
// DetectionPacks (detection_packs.go); MITRE techniques and intent give
// the SOC immediate context when a finding fires; and Tags is the canon
// cross-provider categorization (see tags.go).
type RuleCatalogEntry struct {
	ID              string
	Provider        string
	Title           string
	Description     string
	Severity        string
	EventTypes      []string
	PackID          string
	MitreTechniques []string
	Intent          string
	Tags            []string
}

// RuleCatalog is the registered list of built-in rules. Order is the
// display order in the UI.
var RuleCatalog = []RuleCatalogEntry{
	{
		ID:              "github.public_repository_created",
		Provider:        "GITHUB",
		Title:           "Public GitHub repository created",
		Description:     "A repository was created or changed to public visibility, which can expose source code, secrets, or customer data.",
		Severity:        "CRITICAL",
		EventTypes:      []string{"PUBLIC_REPOSITORY_CREATED", "REPOSITORY_PUBLICIZED"},
		PackID:          "aperio.github.core.v1",
		MitreTechniques: []string{"T1567.001"},
		Intent:          "Adversary publishes a private repo to exfiltrate source, secrets, or customer data outside the tenant boundary.",
		Tags:            []string{TagDataPublicExposure},
	},
	{
		ID:              "github.branch_protection_disabled",
		Provider:        "GITHUB",
		Title:           "GitHub branch protection disabled",
		Description:     "Required reviews, status checks, signed commits, or linear history were removed from a protected branch.",
		Severity:        "HIGH",
		EventTypes:      []string{"BRANCH_PROTECTION_DISABLED", "BRANCH_PROTECTION_RULE_DELETED", "BRANCH_PROTECTION_RULE_UPDATED"},
		PackID:          "aperio.github.core.v1",
		MitreTechniques: []string{"T1562.001"},
		Intent:          "Adversary weakens source-control guardrails so malicious or unreviewed code can reach protected branches.",
		Tags:            []string{TagPolicyWeakened},
	},
	{
		ID:              "github.oauth_app_installed",
		Provider:        "GITHUB",
		Title:           "Risky GitHub OAuth app installed",
		Description:     "A GitHub OAuth or GitHub App installation requested organization, admin, repo, or write-level access.",
		Severity:        "HIGH",
		EventTypes:      []string{"OAUTH_APP_INSTALLED", "GITHUB_APP_INSTALLED", "ORG_OAUTH_APP_ACCESS_APPROVED"},
		PackID:          "aperio.github.core.v1",
		MitreTechniques: []string{"T1528"},
		Intent:          "Adversary obtains a long-lived third-party authorization that can read repositories or administer organization resources.",
		Tags:            []string{TagOAuthRiskyGrant, TagDataAccess},
	},
	{
		ID:              "slack.mfa_disabled",
		Provider:        "SLACK",
		Title:           "Slack multi-factor authentication disabled",
		Description:     "A Slack user disabled MFA, increasing the likelihood of account takeover and lateral movement.",
		Severity:        "CRITICAL",
		EventTypes:      []string{"MFA_DISABLED", "TWO_FACTOR_AUTH_DISABLED"},
		PackID:          "aperio.slack.core.v1",
		MitreTechniques: []string{"T1556.006"},
		Intent:          "Adversary or compromised insider weakens the account's auth posture to maintain access without triggering MFA prompts.",
		Tags:            []string{TagAuthMFAWeakened},
	},
	{
		ID:              "slack.external_shared_channel_created",
		Provider:        "SLACK",
		Title:           "Slack external shared channel created",
		Description:     "A Slack channel was shared with an external organization, expanding conversation and file visibility outside the tenant.",
		Severity:        "HIGH",
		EventTypes:      []string{"EXTERNAL_SHARED_CHANNEL_CREATED", "SHARED_CHANNEL_INVITE_ACCEPTED"},
		PackID:          "aperio.slack.core.v1",
		MitreTechniques: []string{"T1530"},
		Intent:          "Adversary or insider creates an external collaboration path that can leak sensitive files and messages.",
		Tags:            []string{TagDataExternalShare},
	},
	{
		ID:              "slack.workspace_invite_link_enabled",
		Provider:        "SLACK",
		Title:           "Slack workspace invite link enabled",
		Description:     "A public workspace invite link was enabled, allowing uncontrolled joins if the link leaks.",
		Severity:        "MEDIUM",
		EventTypes:      []string{"WORKSPACE_INVITE_LINK_ENABLED", "INVITE_LINK_CREATED"},
		PackID:          "aperio.slack.core.v1",
		MitreTechniques: []string{"T1078"},
		Intent:          "Adversary uses a leaked invite path to enter the collaboration tenant without normal provisioning controls.",
		Tags:            []string{TagPolicyWeakened},
	},
	{
		ID:              "slack.app_installed",
		Provider:        "SLACK",
		Title:           "Third-party Slack app installed",
		Description:     "A third-party Slack app was installed with user, channel, admin, or file scopes.",
		Severity:        "MEDIUM",
		EventTypes:      []string{"APP_INSTALLED", "APP_APPROVED", "APP_SCOPES_APPROVED"},
		PackID:          "aperio.slack.core.v1",
		MitreTechniques: []string{"T1528"},
		Intent:          "Adversary obtains persistent API access to Slack content or user data through a third-party app grant.",
		Tags:            []string{TagOAuthRiskyGrant, TagDataAccess},
	},
	{
		ID:              "okta.admin_role_assigned",
		Provider:        "OKTA",
		Title:           "Okta admin role assigned",
		Description:     "A user was granted an Okta administrator role, expanding their tenant-wide privileges.",
		Severity:        "CRITICAL",
		EventTypes:      []string{"USER_ACCOUNT_PRIVILEGE_GRANT", "USER_ACCOUNT_PRIVILEGE_GRANTED", "ADMIN_ROLE_ASSIGNED", "ROLE_ASSIGNMENT_CREATED"},
		PackID:          "aperio.okta.core.v1",
		MitreTechniques: []string{"T1098.003"},
		Intent:          "Adversary promotes an attacker-controlled identity to administrator to persist and broaden access across the tenant.",
		Tags:            []string{TagIAMPrivilegeEscalation},
	},
	{
		ID:              "okta.mfa_factor_reset",
		Provider:        "OKTA",
		Title:           "Okta MFA factor reset",
		Description:     "A user's MFA factors were reset, which can be abused for account-takeover bypass during phishing.",
		Severity:        "HIGH",
		EventTypes:      []string{"USER_MFA_FACTOR_RESET", "USER_MFA_FACTOR_RESET_ALL", "MFA_FACTOR_RESET"},
		PackID:          "aperio.okta.core.v1",
		MitreTechniques: []string{"T1556.006"},
		Intent:          "Adversary clears MFA factors so the next sign-in can enroll an attacker-controlled device.",
		Tags:            []string{TagAuthMFAWeakened},
	},
	{
		ID:              "okta.password_policy_weakened",
		Provider:        "OKTA",
		Title:           "Okta password policy weakened",
		Description:     "An Okta password policy was changed to relax length, complexity, or rotation requirements.",
		Severity:        "HIGH",
		EventTypes:      []string{"POLICY_LIFECYCLE_UPDATE", "PASSWORD_POLICY_UPDATED"},
		PackID:          "aperio.okta.core.v1",
		MitreTechniques: []string{"T1556"},
		Intent:          "Adversary reduces password strength requirements to make brute-force and credential stuffing viable.",
		Tags:            []string{TagAuthPassword, TagPolicyWeakened},
	},
	{
		ID:              "okta.suspicious_signin",
		Provider:        "OKTA",
		Title:           "Okta suspicious sign-in",
		Description:     "A sign-in matched Okta's suspicious-activity signal (impossible travel, anomalous device, or threat intel hit).",
		Severity:        "MEDIUM",
		EventTypes:      []string{"SECURITY_THREAT_DETECTED", "USER_AUTHENTICATION_FAILED", "USER_SESSION_START"},
		PackID:          "aperio.okta.core.v1",
		MitreTechniques: []string{"T1078.004"},
		Intent:          "Adversary attempts to ride a compromised credential into the tenant using an anomalous device or location.",
		Tags:            []string{TagAuthSuspiciousLogin},
	},
	{
		ID:              "google_workspace.external_sharing_enabled",
		Provider:        "GOOGLE_WORKSPACE",
		Title:           "Google Drive external sharing enabled",
		Description:     "A Drive resource was shared outside the tenant domain or set to a public visibility scope.",
		Severity:        "HIGH",
		EventTypes:      []string{"EXTERNAL_SHARING_ENABLED"},
		PackID:          "aperio.google_workspace.drive.v1",
		MitreTechniques: []string{"T1530"},
		Intent:          "Adversary or insider expands a Drive resource's audience to exfiltrate it through legitimate-looking sharing links.",
		Tags:            []string{TagDataExternalShare, TagPolicyWeakened},
	},
	{
		ID:              "google_workspace.super_admin_granted",
		Provider:        "GOOGLE_WORKSPACE",
		Title:           "Google Workspace Super Admin role granted",
		Description:     "A user was promoted to Super Admin, granting tenant-wide control over Workspace.",
		Severity:        "CRITICAL",
		EventTypes:      []string{"SUPER_ADMIN_GRANTED"},
		PackID:          "aperio.google_workspace.identity.v1",
		MitreTechniques: []string{"T1098.003"},
		Intent:          "Adversary obtains the highest Workspace role to persist, disable controls, and reach any tenant data.",
		Tags:            []string{TagIAMPrivilegeEscalation},
	},
	{
		ID:              "google_workspace.admin_role_granted",
		Provider:        "GOOGLE_WORKSPACE",
		Title:           "Google Workspace admin role granted",
		Description:     "A user received a delegated administrator role, expanding their tenant privileges.",
		Severity:        "HIGH",
		EventTypes:      []string{"ADMIN_ROLE_GRANTED"},
		PackID:          "aperio.google_workspace.identity.v1",
		MitreTechniques: []string{"T1098.003"},
		Intent:          "Adversary expands a foothold by granting an attacker-controlled account a delegated admin role.",
		Tags:            []string{TagIAMPrivilegeEscalation},
	},
	{
		ID:              "google_workspace.risky_oauth_grant",
		Provider:        "GOOGLE_WORKSPACE",
		Title:           "Risky third-party OAuth grant",
		Description:     "A third-party OAuth app was authorized with sensitive scopes that broaden tenant data access.",
		Severity:        "HIGH",
		EventTypes:      []string{"RISKY_OAUTH_GRANT"},
		PackID:          "aperio.google_workspace.drive.v1",
		MitreTechniques: []string{"T1550.001", "T1528"},
		Intent:          "Adversary tricks a user into authorizing an OAuth app that grants long-lived access to mail and drive data.",
		Tags:            []string{TagOAuthRiskyGrant, TagDataAccess},
	},
	{
		ID:              "google_workspace.admin_mfa_not_enforced",
		Provider:        "GOOGLE_WORKSPACE",
		Title:           "Admin MFA enforcement disabled",
		Description:     "Strong authentication enforcement was disabled for an admin, weakening the privileged-account perimeter.",
		Severity:        "HIGH",
		EventTypes:      []string{"ADMIN_MFA_NOT_ENFORCED"},
		PackID:          "aperio.google_workspace.identity.v1",
		MitreTechniques: []string{"T1556.006"},
		Intent:          "Adversary weakens the admin auth posture to keep stolen credentials viable across sessions.",
		Tags:            []string{TagAuthMFAWeakened, TagPolicyWeakened},
	},
	{
		ID:              "google_workspace.admin_external_recovery_email",
		Provider:        "GOOGLE_WORKSPACE",
		Title:           "Admin external recovery email set",
		Description:     "An admin's recovery email was changed to an external domain, creating an out-of-band account-takeover path.",
		Severity:        "HIGH",
		EventTypes:      []string{"ADMIN_EXTERNAL_RECOVERY_EMAIL"},
		PackID:          "aperio.google_workspace.identity.v1",
		MitreTechniques: []string{"T1098.001"},
		Intent:          "Adversary stages an off-tenant recovery path so a future password reset hands them the admin account.",
		Tags:            []string{TagAuthAccountRecovery},
	},
	{
		ID:              "google_workspace.email_forwarding_enabled",
		Provider:        "GOOGLE_WORKSPACE",
		Title:           "Email forwarding enabled",
		Description:     "Mail forwarding or IMAP was enabled on a mailbox, opening a data-exfiltration channel.",
		Severity:        "HIGH",
		EventTypes:      []string{"EMAIL_FORWARDING_ENABLED"},
		PackID:          "aperio.google_workspace.mail.v1",
		MitreTechniques: []string{"T1114.003"},
		Intent:          "Adversary auto-forwards mailbox contents to an attacker-controlled address to silently exfiltrate mail.",
		Tags:            []string{TagEmailForwarding, TagDataExternalShare},
	},
	{
		ID:              "google_workspace.mailbox_delegation_granted",
		Provider:        "GOOGLE_WORKSPACE",
		Title:           "Mailbox delegation granted",
		Description:     "Mailbox delegation was granted, letting another account read or send mail on the mailbox owner's behalf.",
		Severity:        "HIGH",
		EventTypes:      []string{"MAILBOX_DELEGATION_GRANTED"},
		PackID:          "aperio.google_workspace.mail.v1",
		MitreTechniques: []string{"T1098.002"},
		Intent:          "Adversary persists access to the mailbox by delegating it to an attacker-controlled account.",
		Tags:            []string{TagEmailDelegation, TagDataAccess},
	},
	{
		ID:              "google_workspace.legacy_mail_auth_used",
		Provider:        "GOOGLE_WORKSPACE",
		Title:           "Legacy mail authentication used",
		Description:     "A legacy IMAP/SMTP authentication path was used, which bypasses modern MFA and risk-based sign-in controls.",
		Severity:        "HIGH",
		EventTypes:      []string{"LEGACY_MAIL_AUTH_USED"},
		PackID:          "aperio.google_workspace.mail.v1",
		MitreTechniques: []string{"T1078.004", "T1556.006"},
		Intent:          "Adversary rides a legacy protocol that does not enforce MFA, often after harvesting an app password.",
		Tags:            []string{TagAuthLegacyProtocol},
	},
	{
		ID:              "google_workspace.forwarding_delegate_send_as_combo",
		Provider:        "GOOGLE_WORKSPACE",
		Title:           "Forwarding + delegation + send-as combo",
		Description:     "A mailbox simultaneously has forwarding, delegation, and send-as configured, a classic exfiltration staging pattern.",
		Severity:        "CRITICAL",
		EventTypes:      []string{"FORWARDING_DELEGATE_SEND_AS_COMBO"},
		PackID:          "aperio.google_workspace.mail.v1",
		MitreTechniques: []string{"T1114.003", "T1098.002"},
		Intent:          "Adversary stages a multi-vector mailbox takeover that survives password rotation and silently routes mail outbound.",
		Tags:            []string{TagEmailForwarding, TagEmailDelegation, TagDataExternalShare},
	},
	{
		ID:              "ms365.guest_user_invited",
		Provider:        "MICROSOFT_365",
		Title:           "Microsoft 365 guest user invited",
		Description:     "An external B2B guest was invited into the Microsoft 365 tenant.",
		Severity:        "MEDIUM",
		EventTypes:      []string{"GUEST_USER_INVITED", "GUEST_INVITATION_CREATED", "USER_INVITED"},
		PackID:          "aperio.microsoft_365.identity.v1",
		MitreTechniques: []string{"T1133"},
		Intent:          "Adversary or insider adds an external identity that can later be granted tenant application or data access.",
		Tags:            []string{TagDataAccess},
	},
	{
		ID:              "ms365.conditional_access_disabled",
		Provider:        "MICROSOFT_365",
		Title:           "Microsoft 365 conditional access disabled",
		Description:     "A conditional access policy was disabled or moved out of enforcement.",
		Severity:        "CRITICAL",
		EventTypes:      []string{"CONDITIONAL_ACCESS_DISABLED", "CONDITIONAL_ACCESS_POLICY_DISABLED", "CONDITIONAL_ACCESS_POLICY_UPDATED"},
		PackID:          "aperio.microsoft_365.identity.v1",
		MitreTechniques: []string{"T1562.007"},
		Intent:          "Adversary weakens identity controls to bypass MFA, device posture, location, or risk-based access checks.",
		Tags:            []string{TagPolicyWeakened, TagAuthMFAWeakened},
	},
	{
		ID:              "ms365.global_admin_granted",
		Provider:        "MICROSOFT_365",
		Title:           "Microsoft 365 Global Administrator granted",
		Description:     "A user was assigned the Global Administrator role in Entra ID.",
		Severity:        "CRITICAL",
		EventTypes:      []string{"GLOBAL_ADMIN_GRANTED", "DIRECTORY_ROLE_ASSIGNED", "ROLE_ASSIGNMENT_CREATED"},
		PackID:          "aperio.microsoft_365.identity.v1",
		MitreTechniques: []string{"T1098.003"},
		Intent:          "Adversary elevates an identity to tenant-wide administrator to persist, disable controls, and access data.",
		Tags:            []string{TagIAMPrivilegeEscalation},
	},
	{
		ID:              "atlassian.anonymous_access_enabled",
		Provider:        "ATLASSIAN",
		Title:           "Atlassian anonymous access enabled",
		Description:     "A Jira project, Confluence space, or site setting was opened to anonymous users.",
		Severity:        "HIGH",
		EventTypes:      []string{"ANONYMOUS_ACCESS_ENABLED", "PUBLIC_ACCESS_ENABLED"},
		PackID:          "aperio.atlassian.access.v1",
		MitreTechniques: []string{"T1530"},
		Intent:          "Adversary or insider exposes issue, page, attachment, or project data to unauthenticated users.",
		Tags:            []string{TagDataPublicExposure, TagPolicyWeakened},
	},
	{
		ID:              "atlassian.public_space_created",
		Provider:        "ATLASSIAN",
		Title:           "Atlassian public Confluence space created",
		Description:     "A Confluence space or Jira project was created with public visibility.",
		Severity:        "MEDIUM",
		EventTypes:      []string{"PUBLIC_SPACE_CREATED", "SPACE_PUBLIC_ACCESS_ENABLED", "PROJECT_PUBLIC_ACCESS_ENABLED"},
		PackID:          "aperio.atlassian.access.v1",
		MitreTechniques: []string{"T1530"},
		Intent:          "Adversary or insider creates a durable public collaboration area for staged data exposure.",
		Tags:            []string{TagDataPublicExposure},
	},
	{
		ID:              "atlassian.org_admin_granted",
		Provider:        "ATLASSIAN",
		Title:           "Atlassian organization admin granted",
		Description:     "A user was granted Atlassian organization, site, Jira, or Confluence admin privileges.",
		Severity:        "HIGH",
		EventTypes:      []string{"ORG_ADMIN_GRANTED", "SITE_ADMIN_GRANTED", "PRODUCT_ADMIN_GRANTED"},
		PackID:          "aperio.atlassian.access.v1",
		MitreTechniques: []string{"T1098.003"},
		Intent:          "Adversary expands access by assigning broad Atlassian administrative privileges.",
		Tags:            []string{TagIAMPrivilegeEscalation},
	},
	{
		ID:              "salesforce.admin_profile_assigned",
		Provider:        "SALESFORCE",
		Title:           "Salesforce administrator profile assigned",
		Description:     "A user was assigned System Administrator, Modify All Data, or a similarly privileged Salesforce profile or permission set.",
		Severity:        "CRITICAL",
		EventTypes:      []string{"ADMIN_PROFILE_ASSIGNED", "PERMISSION_SET_ASSIGNED", "PROFILE_ASSIGNED"},
		PackID:          "aperio.salesforce.core.v1",
		MitreTechniques: []string{"T1098.003"},
		Intent:          "Adversary gains broad CRM data and configuration control by adding a privileged Salesforce entitlement.",
		Tags:            []string{TagIAMPrivilegeEscalation, TagDataAccess},
	},
	{
		ID:              "salesforce.connected_app_policy_weakened",
		Provider:        "SALESFORCE",
		Title:           "Salesforce connected app policy weakened",
		Description:     "A connected app policy was relaxed to allow broader OAuth, IP, refresh-token, or admin-approved-user access.",
		Severity:        "HIGH",
		EventTypes:      []string{"CONNECTED_APP_POLICY_WEAKENED", "CONNECTED_APP_UPDATED"},
		PackID:          "aperio.salesforce.core.v1",
		MitreTechniques: []string{"T1528"},
		Intent:          "Adversary weakens a Salesforce connected app to obtain or keep long-lived OAuth access to CRM data.",
		Tags:            []string{TagOAuthRiskyGrant, TagPolicyWeakened},
	},
	{
		ID:              "salesforce.report_exported",
		Provider:        "SALESFORCE",
		Title:           "Salesforce bulk report export",
		Description:     "A report, list view, or data export job downloaded a large amount of Salesforce data.",
		Severity:        "HIGH",
		EventTypes:      []string{"REPORT_EXPORTED", "BULK_DATA_EXPORT", "DATA_EXPORT_DOWNLOADED"},
		PackID:          "aperio.salesforce.core.v1",
		MitreTechniques: []string{"T1530"},
		Intent:          "Adversary or insider exports high-value CRM data through legitimate Salesforce reporting or export paths.",
		Tags:            []string{TagDataAccess, TagDataExternalShare},
	},
}

// RuleCatalogForProvider returns the rules registered for a given
// provider, preserving display order. An unknown provider returns nil.
func RuleCatalogForProvider(provider string) []RuleCatalogEntry {
	out := make([]RuleCatalogEntry, 0, 4)
	for _, entry := range RuleCatalog {
		if entry.Provider == provider {
			out = append(out, entry)
		}
	}
	return out
}
